[package]
name = "animated"
version = "0.1.0"
edition = "2021"

[dependencies]
#TerimalRtdm = { git = "https://github.com/had2020/TerimalRtdm" }
TerimalRtdm = { path = "/Users/hadrian/Developer/github_repos/TerimalRtdm" }
